# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TesteAudio' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TesteAudio
   pod 'AudioKit', '~> 4.2'

end
